---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Extra Packages for Enterprise Linux
      
tabs:
  - name: ">_ Terminal"
    port: 443
    path: /wetty
    user: root
    host: rhel
    type: tty
  - name: "RHEL Web Console"
    port: 443
    path: "/cockpit"
