---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Module 1
tabs:
  - name: ">_ Root"
    port: 443
    path: /wetty
    user: root
    host: rhel
    type: tty
  - name: ">_ rhel"
    port: 443
    path: /wetty
  - name: "Cockpit"
    port: 9943
    path: "/cockpit"
